language: node_js

node_js:
  - 6

script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "openssl aes-256-cbc -K $encrypted_35c90b7b3c7c_key -iv $encrypted_35c90b7b3c7c_iv -in deploy_key.enc -out ~\/.ssh/deploy_key -d"
  - COMMIT_AUTHOR_EMAIL: "simon@simonemms.com"