language: node_js
node_js:
  - 6
script:
  - npm run compile
after_success:
  - bash deploy.sh
env:
  global:
    secure: QOMD9bXmU8DX0NXirA79RSv/ZurjkhRQ1deKkGpSGndsAey1xQPBP4Y+uIHrTTB+SualgQ340idFFWiA4vBwUi1Vf6gQw4nlMlobx1qdSo7NAJqXs9OIWg3uU1TE9PErE72AfDlwNNsIE+4dZCRztO8MDO0/rWWdUzSTyYmegF7RQ2TV86wTmumDl4/iPU2cmzzYuRh195WO31qkWGSRWEETvpz8KrnmL6Ln4NKezVgG2zdd3KZF1L2txTN21qrY+LLCLymZl7hdvPEOGftOWWoZ2CM5ukfm4VRxX0aznLL0FQUjh292y91+yv6G1HhuL+KQzcSWCz2JN+sZr3mrlw4OAmBQTT32W3pdiCPQecJ4hiatiNrZdk3PfZeKbhQQJhNnELsWYzJ7Yw4SUBHzB/JpCkrDFYUn1ekU0sTcPk2gD3cFXSvfyYk3UmwByAMtPLK1OcvlurvUOdC5pHrN13co44q9ORrpr3wlp4UfQAAAtn29Gldi4s/cNEXDWeUMY42Hic2mj8DhF8nC5OrShqJW4JjdZyy2KnlvYTBJGSKpbSeuDDXv70J2lZ4MJnLqPBXPLl2hFWU5yD+VGJBmTUkRyqZ1SpOUYkZTsR3aJ0r9cK4O22ayMmjovXZ1+3QxSzcyDapWbIjgtWuu/zY8I/6v+EmFU1ZPtuwrWXasD3I=
